### ISSUE TITLE
Eledees - The Adventures of Kai and Zero (Europe) (En,Fr,De,Es,It) corrupt graphics

### ISSUE THREAD

**Issue by benderscruffy** [Hydr8gon/NooDS#38] opened 2020-06-12 08:49 UTC
the graphics on both screens are corrupt

**Comment by Hydr8gon** [comment] 2020-06-14 06:50
Corrupt how? Can you post a screenshot?

**Comment by benderscruffy** [comment] 2020-06-16 10:46
here is a screenshot
![eledees](https://user-images.githubusercontent.com/2696404/84765346-b072f080-b001-11ea-8f85-8f80a93db7c7.PNG)

**Comment by Hydr8gon** [comment] 2020-06-16 20:42
Another game using the 3D engine for rendering. I guess the textures aren't loading correctly? Weird.

**Comment by Hydr8gon** [comment] 2020-06-16 22:00
The original issue is now fixed by commit bd5e5fe (this game was actually a useful test case for figuring out some shifting shenanigans that were confusing me last time I tried to implement this). But now there's this issue on the title screen:
![Screenshot from 2020-06-16 17-54-36](https://user-images.githubusercontent.com/3057954/84832284-faa4a380-affa-11ea-9a21-48ee4e0fdb67.png)
I guess the swap buffers command is somehow being sent at the wrong time? This is also weird.

**Comment by Hydr8gon** [comment] 2020-08-09 02:01
Oh right, I should give an update since I know what the problem is. The game is overflowing the GXFIFO; it keeps pushing commands even after the swap buffers command, which is dumb. On hardware, writing to the FIFO while it's full freezes the bus until the geometry engine executes enough commands to free space. Currently NooDS just instantly runs commands to free space right away. Normally this is fine, but since the game is overflowing after the geometry engine has halted, it ends up running commands meant for the next frame on the current frame. As for fixing it, I can either do it right (which would require somewhat emulating the bus, yikes) or I can find some other way. We'll see.

**Closed** 2021-04-06 19:54 UTC
Labels: bug
