### ISSUE TITLE
Classic NES games not booting

### ISSUE THREAD

**Issue by benderscruffy** [Hydr8gon/NooDS#14] opened 2020-06-09 10:50 UTC
just a black screen with garbled sound

**Comment by Hydr8gon** [comment] 2020-06-10 01:09
Heh, sorry about the earrape. Apparently these games have some anti-piracy measures that many emulators have struggled with. [This mGBA article](https://mgba.io/2014/12/28/classic-nes/) has lots of information on it. I'll have to take some time to go over it and try to properly handle the tricks these games pull.

**Comment by Hydr8gon** [comment] 2021-06-28 19:11
This is finally fixed with 9ca7aef. I held off on proper pipelining for a while, because it hurt performance and didn't fix the NES games on its own anyway. With the recent memory optimization, it doesn't seem to have any noticeable performance impact in most cases, so yay! As for the NES games, 0966105 fixed the other issue that was breaking them.

There's still an issue with controls in the NES games though. Mirroring the ROM in memory fixes this, but it seems a bit strange to me, considering other games don't do this. I'm going to look into it a bit before committing anything to fix it. Regardless, I think this issue can be closed now.

**Closed by Hydr8gon** 2021-06-28 19:11 UTC
Labels: bug

**Comment by qamichele594** [comment] 2022-01-31 02:27
How are possibly caused by a AP copyprotection lockout in classic nes games?? @Hydr8gon
