### ISSUE TITLE
Issue: Fatal on windows. Mismatch between the program and library build versions

### ISSUE THREAD

**Issue by hax4dazy** [Hydr8gon/NooDS#70] opened 2021-11-01 19:16 UTC
Hey, I tried to run NooDS on two different machines (One running w11 and one on w10) and both machines gave me this error 
![image](https://user-images.githubusercontent.com/16256978/139727960-8128ed28-2709-4868-8683-739e6735a432.png)

I attempted to download an older version of NooDS but it seems like the old release are gone from GitHub.

**Comment by Hydr8gon** [comment] 2021-11-01 20:42
Duplicate of #69. I just reran the autobuild, so the new ones have the updated library. Sorry about that!

**Closed by Hydr8gon** 2021-11-01 20:42 UTC
