### ISSUE TITLE
Can see my folder 

### ISSUE THREAD

**Issue by Dwisantosobk** [Hydr8gon/NooDS#57] opened 2021-08-09 05:46 UTC
Hi masta, i have samsung a71 with android 11,
I can see my folder like download, pictures and others 

So i can run bios or game in my Phone :'(
![Screenshot_20210809-124420](https://user-images.githubusercontent.com/86861327/128664513-de10c011-5498-4e65-8e3c-c30c04651de0.jpg)

**Comment by Hydr8gon** [comment] 2021-08-09 14:09
Er, is the issue that you *can't* see these folders? Even after scrolling down?

Actually, I've had someone report weird issues with the Android file browser before too. I couldn't reproduce it myself for a while, but recently I noticed a couple of ROMs at the bottom of my list are taking on names and icons of other ROMs, which is really strange. I'll have to look into it more.

**Comment by Hydr8gon** [comment] 2021-08-28 21:32
Can you try again with the newest build? If the issue is what I think it is, 6325da2 should fix it.

**Comment by Dwisantosobk** [comment] 2021-08-28 23:21
Finally  i can find my folder games, but i can find my bios7.bin or bios9.bin 
![Screenshot_20210829-061935](https://user-images.githubusercontent.com/86861327/131233334-4b233d20-4b21-4177-99d4-666bfe4f5679.jpg)

**Comment by Hydr8gon** [comment] 2021-08-29 06:28
The BIOS and firmware files need to go in specific locations. By default, they should be:
`noods/bios9.bin`
`noods/bios7.bin`
`noods/firmware.bin`
where `noods` is a folder on the root of your storage. You can also use different paths by editing `noods/noods.ini`.

**Comment by Hydr8gon** [comment] 2021-09-29 21:32
The original issue here was fixed, so I'm closing this.

**Closed by Hydr8gon** 2021-09-29 21:32 UTC
Labels: bug, ui
